# Generated by Django 2.1.3 on 2018-11-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weMusic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='last_changed_time',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='time',
        ),
        migrations.AlterField(
            model_name='song',
            name='num_like',
            field=models.IntegerField(),
        ),
    ]
